# Tarefa 5 - Conjunto de Plantas mais frequentes nos EUA e Canadá

Reference:
http://rasbt.github.io/mlxtend/user_guide/frequent_patterns/association_rules/

In [33]:
import pandas as pd
import numpy as np

## Importação dos dados

In [34]:
def read_listas(name):
    with open(name, 'r') as f:
        lines = f.readlines()
    states = []
    for line in lines:
        states.append(line.strip().split(',')[1:])
    return states

In [35]:
plantas = read_listas("plants.data")

In [36]:
plantas[0]

['fl', 'nc']

## Convertendo a lista para uma matriz binária

In [37]:
#!pip install mlxtend
from mlxtend.preprocessing import TransactionEncoder

In [44]:
te = TransactionEncoder()
te_ary = te.fit(plantas).transform(plantas)

## Transformando a matriz binária em um DataFrame

In [45]:
df = pd.DataFrame(te_ary, columns=te.columns_)
df

,ab,ak,al,ar,az,bc,ca,co,ct,dc,...,tx,ut,va,vi,vt,wa,wi,wv,wy,yt
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True,True,...,False,False,True,True,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,True,...,False,False,True,True,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34776,False,False,False,False,False,False,False,True,False,False,...,False,True,False,False,False,False,False,False,True,False
34777,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
34778,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
34779,False,False,False,False,False,False,True,True,False,False,...,True,False,False,False,False,True,False,False,False,False
34780,False,False,False,False,False,False,True,True,False,False,...,True,False,False,False,False,True,False,False,False,False

## Encontrando conjunto de dados mais frequentes

In [39]:
from mlxtend.frequent_patterns import apriori

In [40]:
ap = apriori(df, min_support=0.15)

In [41]:
ap.head(5)

    support itemsets
0  0.163940      (2)
1  0.194877      (4)
2  0.335701      (6)
3  0.157126      (7)
4  0.190363     (12)

## Utilizando regras de associação

In [42]:
from mlxtend.frequent_patterns import association_rules

In [48]:
# printing out the association rules
rules = association_rules(ap, metric="confidence", min_threshold=0.5)
print(len(rules))

1

## Visualização de regras encontradas

In [49]:
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(50),(6),0.202064,0.335701,0.158765,0.785714,2.340521,0.090932,3.100064

## Salvando as regras encontradas

In [ ]:
with open('regras.txt', 'w') as f:
    f.write('rules')